[WIP] Add `bits` feature; factor out PrimeFieldBits
zkcrypto/ff pull request #42
Opened 2020-09-09 08:27 UTC by tarcieri

(NOTE: breaking change)

Makes `bitvec` an optional dependency by factoring the types and methods which depend on it into their own trait.

2020-09-09 08:31 UTC, tarcieri commented on Cargo.toml
> +rustdoc-args = ["--cfg", "docsrs"]
Wired up `doc_cfg` in this PR. Let me know if you'd like it split out separately, but I think it's nice when you start having several features.

Rendered rustdoc:

<img width="1006" src="https://user-images.githubusercontent.com/797/92574546-12777680-f23c-11ea-8ce2-f5b6ab8574f3.png">

<img width="664" src="https://user-images.githubusercontent.com/797/92574560-173c2a80-f23c-11ea-87d2-b8a26d984e3e.png">

2020-09-09 08:34 UTC, tarcieri commented
The motivation for this change is the `RustCrypto/elliptic-curve` crates don't presently use any of the `bitvec`-dependent functionality, making it (at least presently) a superfluous dependency.

I think for `k256` this might be an indefinite state of affairs, since it already has nicely written field arithmetic backends for both 32-bit and 64-bit architectures, and also implements some nice optimizations like lazy normalization.

2021-02-11 13:17 UTC, tarcieri commented
Rebased this PR and finished up the `ff_derive` parts. The tests now pass.

2021-02-11 13:18 UTC, tarcieri commented on ff_derive/src/lib.rs
> +/// Derive the `PrimeField` trait.
Added this to improve the rustdoc (rendered above)

2021-03-12 04:01 UTC, str4d requested changes
I'm fine with this change overall; a couple of comments.

2021-03-12 14:57 UTC, tarcieri commented on src/lib.rs
> +#![deny(broken_intra_doc_links)] // Catch documentation errors caused by code changes.
Reverted

2021-03-12 15:15 UTC, tarcieri commented
Updated with the suggested changes

2021-03-12 17:11 UTC, str4d commented on src/lib.rs
> -// Catch documentation errors caused by code changes.
Please undo this removal 😃

2021-03-12 17:19 UTC, tarcieri commented on src/lib.rs
> -// Catch documentation errors caused by code changes.
Whoops, done

2021-03-13 17:44 UTC, str4d approved these changes

2021-03-13 17:44 UTC, merged